/*
 * AppConstants
 * Each action has a corresponding type, which the reducer knows and picks up on.
 * To avoid weird typos between the reducer and the actions, we save them as
 * constants here. We prefix them with 'yourproject/YourComponent' so we avoid
 * reducers accidentally picking up actions they shouldn't.
 *
 * Follow this format:
 * export const YOUR_ACTION_CONSTANT = 'yourproject/YourContainer/YOUR_ACTION_CONSTANT';
 */

export const GLOBAL_ERROR_HAPPEN = 'app/App/GLOBAL_ERROR_HAPPEN';
export const GLOBAL_ERROR_CLEAR = 'app/App/GLOBAL_ERROR_CLEAR';
export const DRAWER_OPEN = 'app/App/DRAWER_OPEN';

export const NOTIFICATION_SHOW = 'app/App/NOTIFICATION_SHOW';
export const NOTIFICATION_HIDE = 'app/App/NOTIFICATION_HIDE';

export const UPLOAD_VIDEO = 'app/App/UPLOAD_VIDEO';
export const UPLOAD_VIDEO_SUCCESS = 'app/App/UPLOAD_VIDEO_SUCCESS';
export const UPLOAD_VIDEO_FAIL = 'app/App/UPLOAD_VIDEO_FAIL';
export const UPLOAD_VIDEO_PROGRESS = 'app/App/UPLOAD_VIDEO_PROGRESS';

export const UPLOAD_BANNER = 'app/App/UPLOAD_BANNER';
export const UPLOAD_BANNER_SUCCESS = 'app/App/UPLOAD_BANNER_SUCCESS';
export const UPLOAD_BANNER_FAIL = 'app/App/UPLOAD_BANNER_FAIL';
export const CLEAR_UPLOAD_BANNER_ERROR = 'app/App/CLEAR_UPLOAD_BANNER_ERROR';

export const CREATE_VIDEO = 'app/App/CREATE_VIDEO';
export const CREATE_VIDEO_SUCCESS = 'app/App/CREATE_VIDEO_SUCCESS';
export const CREATE_VIDEO_FAIL = 'app/App/CREATE_VIDEO_FAIL';

export const GET_MY_VIDEOS = 'app/App/GET_MY_VIDEOS';
export const GET_MY_VIDEOS_SUCCESS = 'app/App/GET_MY_VIDEOS_SUCCESS';
export const GET_MY_VIDEOS_FAIL = 'app/App/GET_MY_VIDEOS_FAIL';

export const DELETE_VIDEO = 'app/App/DELETE_VIDEO';
export const DELETE_VIDEO_SUCCESS = 'app/App/DELETE_VIDEO_SUCCESS';
export const DELETE_VIDEO_FAIL = 'app/App/DELETE_VIDEO_FAIL';

export const CLEAR_VIDEO_DATA_AFTER_CREATE =
  'app/App/CLEAR_VIDEO_DATA_AFTER_CREATE';
export const CLEAR_VIDEO_DELETE_ERROR = 'app/App/CLEAR_VIDEO_DELETE_ERROR';

export const GET_VIDEO = 'app/App/GET_VIDEO';
export const GET_VIDEO_SUCCESS = 'app/App/GET_VIDEO_SUCCESS';
export const GET_VIDEO_FAIL = 'app/App/GET_VIDEO_FAIL';

export const CLEAR_GET_VIDEO_AFTER_UNMOUNT =
  'app/App/CLEAR_GET_VIDEO_AFTER_UNMOUNT';
export const CLEAR_GET_VIDEO_ERROR = 'app/App/CLEAR_GET_VIDEO_ERROR';

export const UPDATE_VIDEO = 'app/App/UPDATE_VIDEO';
export const UPDATE_VIDEO_SUCCESS = 'app/App/UPDATE_VIDEO_SUCCESS';
export const UPDATE_VIDEO_FAIL = 'app/App/UPDATE_VIDEO_FAIL';

export const CLEAR_UPDATE_VIDEO_DATA = 'app/App/CLEAR_UPDATE_VIDEO_DATA';

export const GET_STATISTIC = 'app/App/GET_STATISTIC';
export const GET_STATISTIC_SUCCESS = 'app/App/GET_STATISTIC_SUCCESS';
export const GET_STATISTIC_FAIL = 'app/App/GET_STATISTIC_FAIL';

export const CLEAR_GET_STATISTIC_DATA = 'app/App/CLEAR_GET_STATISTIC_DATA';

export const GET_TAGS = 'app/App/GET_TAGS';
export const GET_TAGS_SUCCESS = 'app/App/GET_TAGS_SUCCESS';
export const GET_TAGS_FAIL = 'app/App/GET_TAGS_FAIL';

export const ADD_TAGS = 'app/App/ADD_TAGS';
export const ADD_TAGS_SUCCESS = 'app/App/ADD_TAGS_SUCCESS';
export const ADD_TAGS_FAIL = 'app/App/ADD_TAGS_FAIL';

export const GET_APARAT_CATEGORIES = 'app/App/GET_APARAT_CATEGORIES';
export const GET_APARAT_CATEGORIES_SUCCESS =
  'app/App/GET_APARAT_CATEGORIES_SUCCESS';
export const GET_APARAT_CATEGORIES_FAIL = 'app/App/GET_APARAT_CATEGORIES_FAIL';

export const GET_CHANNEL_CATEGORIES = 'app/App/GET_CHANNEL_CATEGORIES';
export const GET_CHANNEL_CATEGORIES_SUCCESS =
  'app/App/GET_CHANNEL_CATEGORIES_SUCCESS';
export const GET_CHANNEL_CATEGORIES_FAIL =
  'app/App/GET_CHANNEL_CATEGORIES_FAIL';

export const ADD_CHANNEL_CATEGORIES = 'app/App/ADD_CHANNEL_CATEGORIES';
export const ADD_CHANNEL_CATEGORIES_SUCCESS =
  'app/App/ADD_CHANNEL_CATEGORIES_SUCCESS';
export const ADD_CHANNEL_CATEGORIES_FAIL =
  'app/App/ADD_CHANNEL_CATEGORIES_FAIL';

export const EDIT_CHANNEL_CATEGORIES = 'app/App/EDIT_CHANNEL_CATEGORIES';
export const EDIT_CHANNEL_CATEGORIES_SUCCESS =
  'app/App/EDIT_CHANNEL_CATEGORIES_SUCCESS';
export const EDIT_CHANNEL_CATEGORIES_FAIL =
  'app/App/EDIT_CHANNEL_CATEGORIES_FAIL';

export const Upload_CHANNEL_BANNER = 'app/App/Upload_CHANNEL_BANNER';
export const Upload_CHANNEL_BANNER_SUCCESS =
  'app/App/Upload_CHANNEL_BANNER_SUCCESS';
export const Upload_CHANNEL_BANNER_FAIL = 'app/App/Upload_CHANNEL_BANNER_FAIL';

export const GET_PLAYLISTS = 'app/App/GET_PLAYLISTS';
export const GET_PLAYLISTS_SUCCESS = 'app/App/GET_PLAYLISTS_SUCCESS';
export const GET_PLAYLISTS_FAIL = 'app/App/GET_PLAYLISTS_FAIL';

export const ADD_PLAYLIST = 'app/App/ADD_PLAYLIST';
export const ADD_PLAYLIST_SUCCESS = 'app/App/ADD_PLAYLIST_SUCCESS';
export const ADD_PLAYLIST_FAIL = 'app/App/ADD_PLAYLIST_FAIL';

export const GET_FOLLOW_LIST = 'app/App/GET_FOLLOW_LIST';
export const GET_FOLLOW_LIST_SUCCESS = 'app/App/GET_FOLLOW_LIST_SUCCESS';
export const GET_FOLLOW_LIST_FAIL = 'app/App/GET_FOLLOW_LIST_FAIL';
export const CLEAR_GET_FOLLOW_LIST_ERROR =
  'app/App/CLEAR_GET_FOLLOW_LIST_ERROR';

export const UNFOLLOW_CHANNEL = 'app/App/UNFOLLOW_CHANNEL';
export const UNFOLLOW_CHANNEL_SUCCESS = 'app/App/UNFOLLOW_CHANNEL_SUCCESS';
export const UNFOLLOW_CHANNEL_FAIL = 'app/App/UNFOLLOW_CHANNEL_FAIL';

export const FOLLOW_CHANNEL = 'app/App/FOLLOW_CHANNEL';
export const FOLLOW_CHANNEL_SUCCESS = 'app/App/FOLLOW_CHANNEL_SUCCESS';
export const FOLLOW_CHANNEL_FAIL = 'app/App/FOLLOW_CHANNEL_FAIL';

export const GET_COMMENTS = 'app/App/GET_COMMENTS';
export const GET_COMMENTS_SUCCESS = 'app/App/GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_FAIL = 'app/App/GET_COMMENTS_FAIL';

export const POST_COMMENT = 'app/App/POST_COMMENT';
export const POST_COMMENT_SUCCESS = 'app/App/POST_COMMENT_SUCCESS';
export const POST_COMMENT_FAIL = 'app/App/POST_COMMENT_FAIL';
export const CLEAR_POST_COMMENT_ERROR = 'app/App/CLEAR_POST_COMMENT_ERROR';

export const REMOVE_COMMENT = 'app/App/REMOVE_COMMENT';
export const REMOVE_COMMENT_SUCCESS = 'app/App/REMOVE_COMMENT_SUCCESS';
export const REMOVE_COMMENT_FAIL = 'app/App/REMOVE_COMMENT_FAIL';

export const CHANGE_STATE_COMMENT = 'app/App/CHANGE_STATE_COMMENT';
export const CHANGE_STATE_COMMENT_SUCCESS =
  'app/App/CHANGE_STATE_COMMENT_SUCCESS';
export const CHANGE_STATE_COMMENT_FAIL = 'app/App/CHANGE_STATE_COMMENT_FAIL';

export const GET_CHANNEL_STATISTICS = 'app/App/GET_CHANNEL_STATISTICS';
export const GET_CHANNEL_STATISTICS_SUCCESS =
  'app/App/GET_CHANNEL_STATISTICS_SUCCESS';
export const GET_CHANNEL_STATISTICS_FAIL =
  'app/App/GET_CHANNEL_STATISTICS_FAIL';
export const GET_CHANNEL_STATISTICS_CLEAR_DATA =
  'app/App/GET_CHANNEL_STATISTICS_CLEAR_DATA';

export const GET_CHANNEL_INFO = 'app/App/GET_CHANNEL_INFO';
export const GET_CHANNEL_INFO_SUCCESS = 'app/App/GET_CHANNEL_INFO_SUCCESS';
export const GET_CHANNEL_INFO_FAIL = 'app/App/GET_CHANNEL_INFO_FAIL';
export const GET_CHANNEL_INFO_CLEAR_DATA =
  'app/App/GET_CHANNEL_INFO_CLEAR_DATA';

export const GET_USER_ME = 'app/App/GET_USER_ME';
export const GET_USER_ME_SUCCESS = 'app/App/GET_USER_ME_SUCCESS';
export const GET_USER_ME_FAIL = 'app/App/GET_USER_ME_FAIL';

export const LOGOUT = 'app/App/LOGOUT';
export const LOGOUT_SUCCESS = 'app/App/LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'app/App/LOGOUT_FAIL';

export const UNREGISTER_USER = 'app/App/UNREGISTER_USER';
export const UNREGISTER_USER_SUCCESS = 'app/App/UNREGISTER_USER_SUCCESS';
export const UNREGISTER_USER_FAIL = 'app/App/UNREGISTER_USER_FAIL';

export const UPDATE_CHANNEL_INFO = 'app/App/UPDATE_CHANNEL_INFO';
export const UPDATE_CHANNEL_INFO_SUCCESS =
  'app/App/UPDATE_CHANNEL_INFO_SUCCESS';
export const UPDATE_CHANNEL_INFO_FAIL = 'app/App/UPDATE_CHANNEL_INFO_FAIL';

export const UPDATE_USER_SOCIALS = 'app/App/UPDATE_USER_SOCIALS';
export const UPDATE_USER_SOCIALS_SUCCESS =
  'app/App/UPDATE_USER_SOCIALS_SUCCESS';
export const UPDATE_USER_SOCIALS_FAIL = 'app/App/UPDATE_USER_SOCIALS_FAIL';

export const UPDATE_USER_PASSWORD = 'app/App/UPDATE_USER_PASSWORD';
export const UPDATE_USER_PASSWORD_SUCCESS =
  'app/App/UPDATE_USER_PASSWORD_SUCCESS';
export const UPDATE_USER_PASSWORD_FAIL = 'app/App/UPDATE_USER_PASSWORD_FAIL';
export const CLEAR_UPDATE_USER_PASSWORD = 'app/App/CLEAR_UPDATE_USER_PASSWORD';

export const UPDATE_USER_EMAIL_OR_MOBILE =
  'app/App/UPDATE_USER_EMAIL_OR_MOBILE';
export const UPDATE_USER_EMAIL_OR_MOBILE_SUCCESS =
  'app/App/UPDATE_USER_EMAIL_OR_MOBILE_SUCCESS';
export const UPDATE_USER_EMAIL_OR_MOBILE_FAIL =
  'app/App/UPDATE_USER_EMAIL_OR_MOBILE_FAIL';

export const SEND_CHANGE_EMAIL_MOBILE_CONFIRM_CODE =
  'app/App/SEND_CHANGE_EMAIL_MOBILE_CONFIRM_CODE';
export const SEND_CHANGE_EMAIL_MOBILE_CONFIRM_CODE_SUCCESS =
  'app/App/SEND_CHANGE_EMAIL_MOBILE_CONFIRM_CODE_SUCCESS';
export const SEND_CHANGE_EMAIL_MOBILE_CONFIRM_CODE_FAIL =
  'app/App/SEND_CHANGE_EMAIL_MOBILE_CONFIRM_CODE_FAIL';

export const CANCEL_UPDATE_EMAIL_MOBILE = 'app/App/CANCEL_UPDATE_EMAIL_MOBILE';

export const GET_CATEGORIZED_VIDEOS = 'app/App/GET_CATEGORIZED_VIDEOS';
export const GET_CATEGORIZED_VIDEOS_SUCCESS =
  'app/App/GET_CATEGORIZED_VIDEOS_SUCCESS';
export const GET_CATEGORIZED_VIDEOS_FAIL =
  'app/App/GET_CATEGORIZED_VIDEOS_FAIL';

export const LIKE_OR_DISLIKE_VIDEO = 'app/App/LIKE_OR_DISLIKE_VIDEO';
export const LIKE_OR_DISLIKE_VIDEO_SUCCESS =
  'app/App/LIKE_OR_DISLIKE_VIDEO_SUCCESS';
export const LIKE_OR_DISLIKE_VIDEO_FAIL = 'app/App/LIKE_OR_DISLIKE_VIDEO_FAIL';

export const REPUBLISH_VIDEO = 'app/App/REPUBLISH_VIDEO';
export const REPUBLISH_VIDEO_SUCCESS = 'app/App/REPUBLISH_VIDEO_SUCCESS';
export const REPUBLISH_VIDEO_FAIL = 'app/App/REPUBLISH_VIDEO_FAIL';

export const SEARCH_VIDEOS = 'app/App/SEARCH_VIDEOS';
export const SEARCH_VIDEOS_SUCCESS = 'app/App/SEARCH_VIDEOS_SUCCESS';
export const SEARCH_VIDEOS_FAIL = 'app/App/SEARCH_VIDEOS_FAIL';
export const CLEAR_SEARCH_VIDEOS_FAIL = 'app/App/CLEAR_SEARCH_VIDEOS_FAIL';

export const GET_USERS = 'app/App/GET_USERS';
export const GET_USERS_SUCCESS = 'app/App/GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'app/App/GET_USERS_FAIL';

export const UPDATE_USER = 'app/App/UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'app/App/UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'app/App/UPDATE_USER_FAIL';

export const RESET_USER_PASSWORD = 'app/App/RESET_USER_PASSWORD';
export const RESET_USER_PASSWORD_SUCCESS =
  'app/App/RESET_USER_PASSWORD_SUCCESS';
export const RESET_USER_PASSWORD_FAIL = 'app/App/RESET_USER_PASSWORD_FAIL';

export const DELETE_USER = 'app/App/DELETE_USER';
export const DELETE_USER_SUCCESS = 'app/App/DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'app/App/DELETE_USER_FAIL';
export const CLEAR_ELETE_USER_DATA = 'app/App/CLEAR_ELETE_USER_DATA';

export const GET_ALL_VIDEOS_TO_MANAGE = 'app/App/GET_ALL_VIDEOS_TO_MANAGE';
export const GET_ALL_VIDEOS_TO_MANAGE_SUCCESS =
  'app/App/GET_ALL_VIDEOS_TO_MANAGE_SUCCESS';
export const GET_ALL_VIDEOS_TO_MANAGE_FAIL =
  'app/App/GET_ALL_VIDEOS_TO_MANAGE_FAIL';

export const VIDEO_CHANGE_STATE = 'app/App/VIDEO_CHANGE_STATE';
export const VIDEO_CHANGE_STATE_SUCCESS = 'app/App/VIDEO_CHANGE_STATE_SUCCESS';
export const VIDEO_CHANGE_STATE_FAIL = 'app/App/VIDEO_CHANGE_STATE_FAIL';

export const GET_FAVORITE_VIDEOS = 'app/App/GET_FAVORITE_VIDEOS';
export const GET_FAVORITE_VIDEOS_SUCCESS =
  'app/App/GET_FAVORITE_VIDEOS_SUCCESS';
export const GET_FAVORITE_VIDEOS_FAIL = 'app/App/GET_FAVORITE_VIDEOS_FAIL';

export const GET_FOLLOWINGS_VIDEOS = 'app/App/GET_FOLLOWINGS_VIDEOS';
export const GET_FOLLOWINGS_VIDEOS_SUCCESS =
  'app/App/GET_FOLLOWINGS_VIDEOS_SUCCESS';
export const GET_FOLLOWINGS_VIDEOS_FAIL = 'app/App/GET_FOLLOWINGS_VIDEOS_FAIL';

export const GET_CATEGORY_VIDEOS = 'app/App/GET_CATEGORY_VIDEOS';
export const GET_CATEGORY_VIDEOS_SUCCESS =
  'app/App/GET_CATEGORY_VIDEOS_SUCCESS';
export const GET_CATEGORY_VIDEOS_FAIL = 'app/App/GET_CATEGORY_VIDEOS_FAIL';
